---
- name: Set username for Debian
  set_fact:
    nginx_user: "www-data"
  when: ansible_os_family == "Debian" and nginx_user is not defined
  
- name: Set groupname for Debian
  set_fact:
    nginx_user: "www-data"
  when: ansible_os_family == "Debian" and nginx_group is not defined

- name: Set fact for RedHat
  set_fact:
    nginx_user: "nginx"
  when: ansible_os_family == "RedHat" and nginx_user is not defined
  
- name: Set fact for RedHat
  set_fact:
    nginx_group: "nginx"
  when: ansible_os_family == "RedHat" and nginx_group is not defined

- name: install nginx
  package:
    name: nginx
    state: present

- name: copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
    validate: nginx -t -c %s
  notify:
    - restart nginx

- name: Ensure the presence of the conf directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=x,o=x
  with_items:
    - sites-available
    - sites-enabled

- name: copy default vHost
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0600'
    backup: yes
  notify:
    - restart nginx

- name: enable default vHost
  file:
    src: /etc/nginx/sites-available/default
    path: /etc/nginx/sites-enabled/default
    state: link
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart nginx

- name: start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes